'use client';
import { createContext, useContext, useState } from 'react';

const translations = {
  es: {
    // Nav
    "nav.inicio": "Inicio",
    "nav.servicios": "Servicios",
    "nav.nosotros": "Nosotros",
    "nav.contacto": "Contacto",
    "nav.llamar": "Llamar",
    "nav.lang.switch": "Switch to English",
    // Hero
    "hero.titulo.l1": "¡Desde donde estés",
    "hero.titulo.l2": "hasta donde lo necesites!",
    "hero.subtitulo": "Especialistas en",
    "hero.words": "Importaciones|Exportaciones|Courier|Agenciamiento Aduanero|Logística Internacional",
    "hero.cta1": "Cotizar mi envío",
    "hero.cta2": "Contáctanos",
    // Services
    "services.titulo": "Servicios Logísticos",
    "services.vermas": "Ver más",
    "services.importacion": "Importación por Courier",
    "services.importacion.desc": "Recepción de envíos desde el exterior hacia Colombia con liberación rápida puerta a puerta.",
    "services.exportacion": "Exportación por Courier",
    "services.exportacion.desc": "Envíos desde Colombia hacia más de 220 países con trámites simplificados y tránsito express.",
    "services.terrestre": "Envíos Terrestres a Venezuela",
    "services.terrestre.desc": "Transporte terrestre eficiente y de menor costo con cobertura en distintas ciudades.",
    "services.casillero": "Casillero Internacional",
    "services.casillero.desc": "Direcciones en EE.UU., España y China para consolidar compras y optimizar costos.",
    "services.triangulacion": "Triangulación de Envíos",
    "services.triangulacion.desc": "Envíos directos entre países, reduciendo tiempos de tránsito y evitando procesos intermedios.",
    "services.especiales": "Operaciones Especiales",
    "services.especiales.desc": "Exportaciones temporales, reembarques, mercancías peligrosas, calibraciones y reparaciones.",
    // ShowcaseSlider
    "showcase.titulo": "Soluciones que mueven al mundo",
    "showcase.s0.tag": "IMPORTACIONES",
    "showcase.s0.title": "Tu mercancía en Colombia, sin complicaciones",
    "showcase.s0.desc": "Gestionamos cada importación desde el origen hasta tu puerta. Trámites aduaneros, liberación express y seguimiento en tiempo real para que tú solo te preocupes por vender.",
    "showcase.s0.statLine1": "EE.UU · España",
    "showcase.s0.statLine2": "Costa Rica · R. Dominicana",
    "showcase.s0.statlabel": "Destinos con mayor volumen de envío",
    "showcase.s1.tag": "EXPORTACIONES",
    "showcase.s1.title": "Colombia al mundo, con rapidez y confianza",
    "showcase.s1.desc": "Exporta tus productos a más de 220 países con procesos aduaneros simplificados. Somos tu aliado estratégico para conquistar mercados internacionales.",
    "showcase.s1.statlabel": "Países de cobertura global",
    "showcase.s2.tag": "CASILLERO INTERNACIONAL",
    "showcase.s2.title": "Compra en el exterior como si estuvieras allá",
    "showcase.s2.desc": "Tenemos direcciones en EE.UU., España y China para que compres en cualquier tienda internacional y recibas tus productos directamente en Colombia.",
    "showcase.s2.statNum": "3 países",
    "showcase.s2.statlabel": "Con direcciones disponibles",
    "showcase.s3.tag": "RED GLOBAL",
    "showcase.s3.title": "Una red logística que no tiene fronteras",
    "showcase.s3.desc": "Operamos con aliados estratégicos en los principales hubs logísticos del mundo. Tu carga siempre estará en manos expertas, sin importar el destino.",
    "showcase.s3.statlabel": "Paquetes despachados en 2025 y 2026",
    // About
    "about.titulo": "Sobre Nosotros",
    "about.p1a": "En ",
    "about.p1b": " somos especialistas en logística internacional aérea, brindando soluciones integrales en importaciones y exportaciones, garantizando rapidez, seguridad y confiabilidad en cada operación.",
    "about.p2": "Gestionamos cada envío con altos estándares de precisión y control, respaldados por un equipo comprometido en ofrecer un servicio personalizado en todas las etapas del proceso logístico.",
    "about.p3": "Más que transportar mercancías, facilitamos el comercio internacional y generamos oportunidades que impulsan el crecimiento de nuestros clientes a nivel global.",
    "about.cta": "Conoce a nuestro equipo",
    // Stats
    "stats.clientes": "Clientes han confiado en nosotros",
    "stats.operaciones": "Operaciones realizadas",
    "stats.kg": "Enviados exitosamente",
    "stats.volumen": "Transportados en volumen",
    // WhyUs
    "whyus.titulo": "¿Por qué elegirnos?",
    "whyus.exp.t": "Experiencia",
    "whyus.exp.d": "Amplia experiencia en logística internacional, gestionando envíos de forma segura, eficiente y sin contratiempos.",
    "whyus.red.t": "Red Global",
    "whyus.red.d": "Aliados estratégicos en más de 220 países, garantizando cobertura global y soluciones confiables.",
    "whyus.aten.t": "Atención Personalizada",
    "whyus.aten.d": "Acompañamiento en todo el proceso con soluciones adaptadas a las necesidades de tu negocio.",
    "whyus.inno.t": "Innovación",
    "whyus.inno.d": "Tecnología avanzada para el seguimiento y gestión de envíos, brindando transparencia y control total.",
    // Process
    "process.titulo": "Nuestro Proceso",
    "process.subtitulo": "Un proceso optimizado para garantizar tu satisfacción en cada etapa del envío.",
    "process.s1.t": "Cotiza con nuestro equipo",
    "process.s1.d": "¿Necesitas mover tu carga? ¡Estamos aquí para ayudarte! Habla con nuestro equipo, recibe asesoría personalizada y cotiza fácil y rápido por WhatsApp o llamada.",
    "process.s2.t": "Infórmanos tus datos de recolección",
    "process.s2.d": "Compártenos la información de recolección y nuestro equipo se encargará de coordinar toda la logística de forma rápida, segura y eficiente. ¡Nosotros nos ocupamos del resto!",
    "process.s3.t": "Paga tu envío de manera ágil",
    "process.s3.d": "Te ofrecemos varios métodos de pago para tu comodidad: transferencia bancaria, tarjeta de crédito o billeteras virtuales. ¡Rápido, seguro y sin complicaciones!",
    "process.s4.t": "Recibe seguimiento en tiempo real",
    "process.s4.d": "Te mantenemos informado en todo momento. Recibe actualizaciones de tu envío, desde la recolección hasta la entrega, directamente en tu correo o WhatsApp.",
    // CTA
    "cta.titulo": "¿Listo para enviar tu mercancía?",
    "cta.subtitulo": "Calcula el peso volumétrico de tu envío y cotiza en minutos.",
    "cta.calc.titulo": "Calculadora de peso volumétrico",
    "cta.calc.desc": "Tu paquete se factura por el peso mayor entre el físico y el volumétrico.",
    "cta.largo": "Largo (cm)",
    "cta.ancho": "Ancho (cm)",
    "cta.alto": "Alto (cm)",
    "cta.peso": "Peso físico (kg) — opcional",
    "cta.vol.label": "Peso volumétrico",
    "cta.facturable": "Peso facturable (el mayor):",
    "cta.cta.titulo": "¿Necesitas una cotización?",
    "cta.cta.desc": "Nuestro equipo te asesora sin compromiso. Escríbenos por WhatsApp o llámanos directamente.",
    "cta.wa": "Cotizar por WhatsApp",
    "cta.pagos": "Medios de pago aceptados",
    "cta.vol.unidad": "volumétrico",
    "cta.fis.unidad": "físico",
    // ServiceModal tabs
    "modal.tab0": "¿Qué es?",
    "modal.tab1": "¿Cómo funciona?",
    "modal.tab2": "¿Ideal para?",
    "modal.queincluye": "¿Qué incluye?",
    "modal.proximamente": "Próximamente disponible.",
    "modal.cotizar": "Cotizar este servicio",
    "modal.cerrar": "Cerrar",
    "modal.wamsg": "Hola, me interesa el servicio de",
    // ContactForm
    "contact.words": "¿Listo para tu próximo envío internacional?|¿Necesitas importar o exportar?|¿Buscas un aliado logístico confiable?",
    "contact.subtitulo": "Nos alegra que estés aquí. Cuéntanos tu necesidad y un asesor de Atlas Logistic te contactará muy pronto.",
    "contact.nombre": "Nombre completo",
    "contact.celular": "Celular",
    "contact.correo": "Correo electrónico",
    "contact.ciudad": "Ciudad",
    "contact.servicio": "Servicio de interés",
    "contact.svc1": "Importación por Courier",
    "contact.svc2": "Exportación por Courier",
    "contact.svc3": "Envíos Terrestres a Venezuela",
    "contact.svc4": "Casillero Internacional",
    "contact.svc5": "Triangulación de Envíos",
    "contact.svc6": "Operaciones Especiales",
    "contact.mensaje": "Mensaje",
    "contact.datos": "Acepto la",
    "contact.datos.politica": "política de tratamiento de datos",
    "contact.datos.aviso": "aviso de privacidad",
    "contact.datos.y": "y el",
    "contact.newsletter": "Acepto recibir información sobre servicios y novedades",
    "contact.enviar": "Enviar mensaje",
    "contact.enviando": "Enviando...",
    "contact.datos.error": "* Debes aceptar la política de tratamiento de datos para continuar",
    "contact.success.p1": "Tu mensaje ha sido enviado correctamente. Agradecemos tu interés en nuestros servicios. Muy pronto uno de nuestros asesores se comunicará contigo para brindarte la información que necesitas.",
    "contact.success.p2": "Mientras tanto, te invitamos a conocer todos nuestros servicios logísticos.",
    "contact.success.ver": "Ver servicios",
    "contact.success.inicio": "Volver al inicio",
    "contact.success.titulo1": "¡Gracias por contactarte con ",
    "contact.success.titulo2": "Atlas!",
    // Footer
    "footer.desc": "Operador Logístico Integral en Colombia. Especialistas en logística internacional aérea, importaciones y exportaciones por courier. ¡Desde donde estés, hasta donde lo necesites!",
    "footer.rights": "Todos los derechos reservados.",
    "footer.city": "Bogotá, Colombia",
  },
  en: {
    // Nav
    "nav.inicio": "Home",
    "nav.servicios": "Services",
    "nav.nosotros": "About",
    "nav.contacto": "Contact",
    "nav.llamar": "Call",
    "nav.lang.switch": "Cambiar a Español",
    // Hero
    "hero.titulo.l1": "From wherever you are,",
    "hero.titulo.l2": "to wherever you need it!",
    "hero.subtitulo": "Specialists in",
    "hero.words": "Imports|Exports|Courier|Customs Agency|International Logistics",
    "hero.cta1": "Quote my shipment",
    "hero.cta2": "Contact us",
    // Services
    "services.titulo": "Logistics Services",
    "services.vermas": "Learn more",
    "services.importacion": "Import by Courier",
    "services.importacion.desc": "Receiving shipments from abroad to Colombia with fast door-to-door clearance.",
    "services.exportacion": "Export by Courier",
    "services.exportacion.desc": "Shipments from Colombia to over 220 countries with simplified procedures and express transit.",
    "services.terrestre": "Land Shipping to Venezuela",
    "services.terrestre.desc": "Efficient and cost-effective land transport with coverage in various cities.",
    "services.casillero": "International Mailbox",
    "services.casillero.desc": "Addresses in the US, Spain and China to consolidate purchases and optimize costs.",
    "services.triangulacion": "Shipment Triangulation",
    "services.triangulacion.desc": "Direct shipments between countries, reducing transit times and avoiding intermediate processes.",
    "services.especiales": "Special Operations",
    "services.especiales.desc": "Temporary exports, transshipments, hazardous goods, calibrations and repairs.",
    // ShowcaseSlider
    "showcase.titulo": "Solutions that move the world",
    "showcase.s0.tag": "IMPORTS",
    "showcase.s0.title": "Your goods in Colombia, hassle-free",
    "showcase.s0.desc": "We manage every import from origin to your door. Customs procedures, express clearance and real-time tracking so you only worry about selling.",
    "showcase.s0.statLine1": "USA · Spain",
    "showcase.s0.statLine2": "Costa Rica · Dominican Rep.",
    "showcase.s0.statlabel": "Top destinations by shipping volume",
    "showcase.s1.tag": "EXPORTS",
    "showcase.s1.title": "Colombia to the world, fast and reliable",
    "showcase.s1.desc": "Export your products to over 220 countries with simplified customs processes. We are your strategic partner to conquer international markets.",
    "showcase.s1.statlabel": "Countries of global coverage",
    "showcase.s2.tag": "INTERNATIONAL MAILBOX",
    "showcase.s2.title": "Shop abroad as if you were there",
    "showcase.s2.desc": "We have addresses in the US, Spain and China so you can shop at any international store and receive your products directly in Colombia.",
    "showcase.s2.statNum": "3 countries",
    "showcase.s2.statlabel": "With available addresses",
    "showcase.s3.tag": "GLOBAL NETWORK",
    "showcase.s3.title": "A logistics network with no borders",
    "showcase.s3.desc": "We operate with strategic partners at the world's main logistics hubs. Your cargo will always be in expert hands, no matter the destination.",
    "showcase.s3.statlabel": "Packages dispatched in 2025 and 2026",
    // About
    "about.titulo": "About Us",
    "about.p1a": "At ",
    "about.p1b": " we specialize in international air logistics, providing comprehensive solutions for imports and exports, ensuring speed, security and reliability in every operation.",
    "about.p2": "We manage every shipment with high standards of precision and control, backed by a team committed to offering personalized service at every stage of the logistics process.",
    "about.p3": "More than transporting goods, we facilitate international trade and create opportunities that drive our clients' growth globally.",
    "about.cta": "Meet our team",
    // Stats
    "stats.clientes": "Clients have trusted us",
    "stats.operaciones": "Operations completed",
    "stats.kg": "Successfully shipped",
    "stats.volumen": "Transported in volume",
    // WhyUs
    "whyus.titulo": "Why choose us?",
    "whyus.exp.t": "Experience",
    "whyus.exp.d": "Extensive experience in international logistics, managing shipments safely, efficiently and without setbacks.",
    "whyus.red.t": "Global Network",
    "whyus.red.d": "Strategic partners in over 220 countries, ensuring global coverage and reliable solutions.",
    "whyus.aten.t": "Personalized Service",
    "whyus.aten.d": "Support throughout the process with solutions tailored to your business needs.",
    "whyus.inno.t": "Innovation",
    "whyus.inno.d": "Advanced technology for shipment tracking and management, providing transparency and total control.",
    // Process
    "process.titulo": "Our Process",
    "process.subtitulo": "An optimized process to guarantee your satisfaction at every stage of the shipment.",
    "process.s1.t": "Get a quote from our team",
    "process.s1.d": "Need to move your cargo? We're here to help! Talk to our team, get personalized advice and quote quickly via WhatsApp or phone.",
    "process.s2.t": "Share your pickup details",
    "process.s2.d": "Share your pickup information and our team will coordinate all logistics quickly, safely and efficiently. We'll take care of the rest!",
    "process.s3.t": "Pay for your shipment easily",
    "process.s3.d": "We offer various payment methods for your convenience: bank transfer, credit card or digital wallets. Fast, secure and hassle-free!",
    "process.s4.t": "Get real-time tracking",
    "process.s4.d": "We keep you informed at all times. Receive shipment updates, from pickup to delivery, directly to your email or WhatsApp.",
    // CTA
    "cta.titulo": "Ready to ship your goods?",
    "cta.subtitulo": "Calculate the volumetric weight of your shipment and quote in minutes.",
    "cta.calc.titulo": "Volumetric weight calculator",
    "cta.calc.desc": "Your package is billed by the greater of physical and volumetric weight.",
    "cta.largo": "Length (cm)",
    "cta.ancho": "Width (cm)",
    "cta.alto": "Height (cm)",
    "cta.peso": "Physical weight (kg) — optional",
    "cta.vol.label": "Volumetric weight",
    "cta.facturable": "Billable weight (the greater):",
    "cta.cta.titulo": "Need a quote?",
    "cta.cta.desc": "Our team advises you without obligation. Message us on WhatsApp or call us directly.",
    "cta.wa": "Quote via WhatsApp",
    "cta.pagos": "Accepted payment methods",
    "cta.vol.unidad": "volumetric",
    "cta.fis.unidad": "physical",
    // ServiceModal tabs
    "modal.tab0": "What is it?",
    "modal.tab1": "How does it work?",
    "modal.tab2": "Ideal for?",
    "modal.queincluye": "What does it include?",
    "modal.proximamente": "Coming soon.",
    "modal.cotizar": "Quote this service",
    "modal.cerrar": "Close",
    "modal.wamsg": "Hello, I'm interested in the service of",
    // ContactForm
    "contact.words": "Ready for your next international shipment?|Need to import or export?|Looking for a reliable logistics partner?",
    "contact.subtitulo": "We're glad you're here. Tell us your needs and an Atlas Logistic advisor will contact you soon.",
    "contact.nombre": "Full name",
    "contact.celular": "Phone",
    "contact.correo": "Email",
    "contact.ciudad": "City",
    "contact.servicio": "Service of interest",
    "contact.svc1": "Import by Courier",
    "contact.svc2": "Export by Courier",
    "contact.svc3": "Land Shipping to Venezuela",
    "contact.svc4": "International Mailbox",
    "contact.svc5": "Shipment Triangulation",
    "contact.svc6": "Special Operations",
    "contact.mensaje": "Message",
    "contact.datos": "I accept the",
    "contact.datos.politica": "data processing policy",
    "contact.datos.aviso": "privacy notice",
    "contact.datos.y": "and the",
    "contact.newsletter": "I accept to receive information about services and news",
    "contact.enviar": "Send message",
    "contact.enviando": "Sending...",
    "contact.datos.error": "* You must accept the data processing policy to continue",
    "contact.success.p1": "Your message has been sent successfully. We appreciate your interest in our services. One of our advisors will contact you very soon.",
    "contact.success.p2": "In the meantime, we invite you to explore all our logistics services.",
    "contact.success.ver": "View services",
    "contact.success.inicio": "Back to top",
    "contact.success.titulo1": "Thank you for contacting ",
    "contact.success.titulo2": "Atlas!",
    // Footer
    "footer.desc": "Comprehensive Logistics Operator in Colombia. Specialists in international air logistics, imports and exports by courier. From wherever you are, to wherever you need it!",
    "footer.rights": "All rights reserved.",
    "footer.city": "Bogotá, Colombia",
  }
};

export const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("es");
  const toggleLang = () => setLang(l => l === "es" ? "en" : "es");
  const t = (key) => translations[lang]?.[key] ?? translations["es"]?.[key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
